### ISSUE TITLE
Can't add a specific URL 

### ISSUE THREAD

**Issue by bitcoinuser** [sepehr-safari/pinstr#12]
Hi,
 
I can't add the specific URL https://addslice.com/

Appear this error: An error has been occured, please try again.

![Captura de tela de 2023-09-23 23-05-08](https://github.com/sepehr-safari/pinstr/assets/1178856/743e02b0-aa00-4b6a-b8a5-28fb68db817b)

**Comment by sepehr-safari** [comment]
that error occur for fetching link preview, cause your link is somehow preventing automatic fetches. so not a big problem, you just need to fill the rest of the form manually.
