### ISSUE TITLE
Enable reordering information tiles within a pin

### ISSUE THREAD

**Issue by bitcoin21ideas** [sepehr-safari/pinstr#13]
When a custom feature is inserted into the pin, it stays solid, not allowing you to reorder these features (tiles) or rename the title. So if a user decides to add another block of info into a pin, he's stuck with it being displayed at the very bottom.

**Comment by sepehr-safari** [comment]
thank you for your suggestion.
implemented in this commit: https://github.com/sepehr-safari/pinstr/commit/0e9eb1091dd32db8eed965b05001f08c6793bc32
