### ISSUE TITLE
Objects overlap

### ISSUE THREAD

**Issue by bitcoin21ideas** [sepehr-safari/pinstr#14]
When opening a link to a board on mobile, the footer covers the "load more" button.

Issue does not seem to occur when opening a website and then navigating to a board.

![overlap-screenshot](https://i.nostr.build/o02x.jpg)

**Comment by sepehr-safari** [comment]
thank you for this bug report.
fixed in this commit: https://github.com/sepehr-safari/pinstr/commit/4c9ede28baebff5d4ccc3de4568ea8c2d7917c3c
