### ISSUE TITLE
Images are not being uploaded when adding a pin

### ISSUE THREAD

**Issue by thetronjohnson** [sepehr-safari/pinstr#18]
Steps to recreate - 

1. Create a new board
2. Add a new pin to a board
3. Upload an image - the image fails to upload

This prevents from adding a pin as the image field is required

Browser version: Firefox 119.0
Operating System: MacOS

**Comment by sepehr-safari** [comment]
uploads are powered by https://nostr.build api and it's currently working fine.

**Comment by thetronjohnson** [comment]
@sepehr-safari just tested it out, working as expected. Thanks
