### ISSUE TITLE
Cannot add pins - add pin button greyed out

### ISSUE THREAD

**Issue by Liadan44** [sepehr-safari/pinstr#19]
Using a mac laptop and firefox browser. Signed in to pinstr using Alby extension. 
I created a board today, choosing the "Create a new board of links" option. I clicked on the board to open it, then clicked "add pin". In the window that opens the "add pin" button is greyed out. The "back" and "cancel" buttons are active. I filled out the three fields: page url, description, and image url. The "add pin" button remains inactive. I canceled and tried again, then closed and reopened pinstr and tried again with the same result.

**Comment by sepehr-safari** [comment]
fixed https://github.com/sepehr-safari/pinstr/pull/20
