### ISSUE TITLE
I'm unable to add a pin with a link: https://bitbo.io

### ISSUE THREAD

**Issue by bitcoinuser** [sepehr-safari/pinstr#22]
Hi,

I'm unable to add a pin with a link: https://bitbo.io

![Captura de tela de 2023-12-08 19-25-54](https://github.com/sepehr-safari/pinstr/assets/1178856/3c488600-9589-49a5-b86f-bf146a65a55b)

**Comment by sepehr-safari** [comment]
I've created a test board and successfully added this https://bitbo.io/ link.
https://pinstr.app/p/npub18c556t7n8xa3df2q82rwxejfglw5przds7sqvefylzjh8tjne28qld0we7/test%20link

could you please open the "Developer Tools" within your "Chrome" and send a screenshot from the "Console" tab as the error came up?

**Comment by bitcoinuser** [comment]
Hi, this helps?

![Captura de tela de 2024-01-22 15-29-22](https://github.com/sepehr-safari/pinstr/assets/1178856/dc74f78b-789f-4d0d-8388-ee8ac680c19c)

**Comment by sepehr-safari** [comment]
something is causing problems for connections in your browser. I don't know what exactly is. it might be an extension which is blocking your connections, or even your browser itself. please test with a clean chrome browser if you can.

**Comment by bitcoinuser** [comment]
Hum, I tested with Firefox with only Alby extension installed and I have the same issue. I think it's not related to extensions installed.

**Comment by bitcoinuser** [comment]
> Hum, I tested with Firefox with only Alby extension installed and I have the same issue. I think it's not related to extensions installed.

![Captura de tela de 2024-01-22 16-08-27](https://github.com/sepehr-safari/pinstr/assets/1178856/5b2bd815-34b7-4845-87ac-1ea6e981527c)

**Comment by bitcoinuser** [comment]
> it obviously says "A resource is blocked". your browser is blocking connections to that specific web url. can you test with some other urls? by the way, you can still fill the form manually. just ignore the errors. fill the form and add your pin. it should work.

I tested with other URL's, I tested with Firefox, Opera and Brave. Same problem with all browsers.

**Comment by sepehr-safari** [comment]
fixed https://github.com/sepehr-safari/pinstr/commit/cb2007217a3f409ff1de0507e2ba06f1eefeeb02
