### ISSUE TITLE
Adding links shouldn't ask to upload images, should use site preview

### ISSUE THREAD

**Issue by bitcoinuser** [sepehr-safari/pinstr#5]
Hi, great project.

Adding links shouldn't ask to upload images, should use site preview.

Thanks

**Comment by sepehr-safari** [comment]
thanks, just implemented in this commit: https://github.com/sepehr-safari/pinstr/commit/fd228a8af8e1ccbd57dcd8ea519fbdf414d27db1

**Comment by bitcoinuser** [comment]
Just to know, this was not applied on pinstr.app site yet, right?
