### ISSUE TITLE
If I add a Pin that is a link, I would like to see all notes of Nostr network that has this link

### ISSUE THREAD

**Issue by bitcoinuser** [sepehr-safari/pinstr#6]
Hi,

If I add a Pin that is a link, I would like to see all notes of Nostr network that has this link. So if someone post a note on nostr network with the same link, this will appear in pinstr on my link pin.
Would be good to have option to add comment on Pins too and not only on Board.

Thanks.

**Comment by sepehr-safari** [comment]
that's not something related to pinstr. you should search for notes by yourself (with any approach you like) and then pin whatever note you want to your board.

**Comment by bitcoinuser** [comment]
Ok, understood. But what do you think about be able to comment on pins too instead of only on boards?

Thanks

**Comment by sepehr-safari** [comment]
I don't think so. because comments should be referenced to a unique nostr event, and there is no separate event for each pin item. we're just using a single Parametrized Replaceable Event for each board.
